spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tabling
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
                use_sql_comments: true
        hibernate:
            ddl-auto: update

logging :
    level:
        root: INFO

jwt:
    secret:
        key: I47PW4GYmNXlx/ydXiSXZTyYirkvSZawfgyOLzt0jbc=
    expiration: 86400000  # 24?? (??? ??)
